### PR TITLE
Add env var support for time

### PR DESCRIPTION
**Pull request by Macleykun**
here ya go fam :) users can just specify the envs and then it works! test this aswell in the container!

PS. don't forget to create a dockerhub, repository in dockerhub and set the secrets in your workflow here on github so that ya next push to main will make the images (and change the references to my image to yours :D)

### CODE REVIEW

**Comment by Macleykun** [comment]
had to edit it sadly that users can only submit full hours only

**Comment by Macleykun** [comment]
Heya! Got a fun update to show!
https://youtu.be/HLGYNhvvlfQ

**Comment by mklements** [comment]
Hey, sorry I've been away for the past two weeks, so haven't gotten much done.
I tried creating a Docker Repo just before going away and didn't come right - I haven't tried hosting an image on Docker before so need to do a bit more reading there.
Congrats on the Novaspirit Tech review feature, it seems like he had a pretty easy time getting it up and running!

**Comment by Macleykun** [comment]
heyo, welcome back!
I think [this video](https://www.youtube.com/watch?v=HwATG0ygxzU) might help ya alot :) i believe it even uses the same workflow!
and yup true! aside of kinda glossing over the timer stuff, it went pretty smoothly :D

**Comment by mklements** [comment]
Thanks for the link, that helped a lot!
It looks like it is building correctly at the moment so will hopefully be up soon.

**Pull request merged**
